version: 2.1

jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: |
          docker login -u "reddy1991" -p "Reddy_1991"
          docker version
          apk add make
          make build-push CI_NAME=circleci

workflows:
  build:
    jobs:
      - build:
          name: build

  nightly:
    triggers:
       - schedule:
           cron: "0 2 * * 0"
           filters:
             branches:
               only:
                 - master
                 - main
    jobs:
      - build:
          name: build
          filters:
            branches:
              only:
                - master
                - main
